apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ include "kross.namespace" . }}
  labels:
    {{- include "kross.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ include "kross.namespace" . }}
  labels:
    {{- include "kross.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "kross.labels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      {{- include "kross.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args: ["redis-server", "--save", "", "--appendonly", "no"]
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: 5
