apiVersion: v1
kind: Secret
metadata:
  name: kross-secrets
  namespace: {{ include "kross.namespace" . }}
  labels:
    {{- include "kross.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  credential-master-key: {{ .Values.secrets.credentialMasterKey | quote }}
  s3-access-key: {{ .Values.secrets.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.secrets.s3SecretKey | quote }}
  juicefs-metaurl: {{ printf "postgres://kross:%s@postgres:5432/%s?sslmode=disable" .Values.secrets.postgresPassword .Values.juicefs.metaDatabase | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: juicefs-sc-secret
  namespace: {{ include "kross.namespace" . }}
  labels:
    {{- include "kross.labels" . | nindent 4 }}
type: Opaque
stringData:
  name: {{ .Values.juicefs.volumeName | quote }}
  metaurl: {{ printf "postgres://kross:%s@postgres:5432/%s?sslmode=disable" .Values.secrets.postgresPassword .Values.juicefs.metaDatabase | quote }}
  storage: s3
  bucket: {{ printf "http://rustfs:9000/%s" .Values.juicefs.bucket | quote }}
  access-key: {{ .Values.secrets.s3AccessKey | quote }}
  secret-key: {{ .Values.secrets.s3SecretKey | quote }}
